version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.15
    container_name: es01
    environment:
      - node.name=es01
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.15
    container_name: kib01
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elastic

  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - elastic
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - elastic

  postgresql:
    image: postgres
    container_name: store_postgre
    environment:
      - POSTGRES_USER=sample_store
      - POSTGRES_PASSWORD=sample_store
      - POSTGRES_DB=sample_store
    ports:
      - 5434:5432
    networks:
      - elastic
    volumes:
      - postgresql_data:/var/lib/postgresql/data

networks:
  elastic:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  postgresql_data:
    driver: local